//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseMasterSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_reports
    {
        public Nullable<int> user_id { get; set; }
        public string report_name { get; set; }
        public string connection { get; set; }
        public int id { get; set; }
    }
}
